#!/bin/bash

echo "===== 修复 VPS 环境变量 ====="
echo ""
echo "请在 VPS 服务器上执行以下命令："
echo ""
echo "# 1. SSH 登录 VPS"
echo "ssh root@76.13.98.3"
echo ""
echo "# 2. 进入项目目录"
echo "cd /root/FeedoBridge"
echo ""
echo "# 3. 编辑 .env 文件"
echo "nano .env"
echo ""
echo "# 4. 找到 SCOPES 这一行，改为："
echo 'SCOPES="read_products,write_products,read_customers,write_customers,read_orders,write_orders"'
echo ""
echo "# 5. 保存文件 (Ctrl+O, Enter, Ctrl+X)"
echo ""
echo "# 6. 重启 Docker 容器"
echo "docker compose restart app"
echo ""
echo "# 7. 等待 10 秒后验证"
echo "sleep 10"
echo 'curl "https://shopifyapp.xmasforest.com/api/check-config" | jq .SCOPES'
echo ""
echo "应该显示完整的 6 个权限！"
echo ""
echo "====================================="
