#!/bin/bash

echo "====== 等待用户重新安装应用 ======"
echo ""
echo "安装完成后，请立即运行以下命令验证："
echo ""
echo "1. 检查数据库记录："
echo "   curl https://shopifyapp.xmasforest.com/api/test-db?shop=feedogostore.myshopify.com"
echo ""
echo "2. 检查 access token："
echo "   curl https://shopifyapp.xmasforest.com/api/debug-token?shop=feedogostore.myshopify.com"
echo ""
echo "3. 注册 webhooks："
echo "   curl https://shopifyapp.xmasforest.com/api/webhooks/register?shop=feedogostore.myshopify.com"
echo ""
echo "4. 保存设置："
echo "   curl -X POST 'https://shopifyapp.xmasforest.com/api/settings?shop=feedogostore.myshopify.com' \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{\"feedogoBaseUrl\": \"https://shop.feedogocloud.com\"}'"
echo ""
echo "======================================"
